### ISSUE TITLE
Allow background & popup together

### ISSUE THREAD

**Issue by fm-sys** [ueen/SnapdropFirefoxAddon#1]
First of all - very great work! Improves my workflow even more :-)

Do you plan to allow running the add-on in background & popup mode? At the moment, only either or is possible...

**Comment by ueen** [comment]
I think it might be possible, but I don't see the point, in background more you get the notifications and in pop-up mode you get the GUI but the result is the same, you receive files and texts, unfortunately sending from popup is not possible due to a kind of bug in Firefox, the popup is closed if a file choose dialog is opened. Therefore, if background mode is activated, and you click on the icon a new tab is opened, so that you can send files and texts, this seems like the optimal solution.
But feel free to convince me otherwise ;)

**Comment by fm-sys** [comment]
OK, just realized that sending files in popup mode does not work at all. So opening the current popup implementation doesn't make sense.

**Comment by ueen** [comment]
Yea you're right, I saw a bug report filed to Mozilla  a while ago, but I'm not sure if it's going to be fixed or if it's kind of by design...

**Comment by fm-sys** [comment]
Very sad that Firefox does not plan to allow PWA's. It would be nice if Snapdrop could come up with a bit more program-like UI. What about opening Snapdrop (optionally) in a website popup?

Java Script:
```
window.open("https://snapdrop.net","_blank",'width=360,height=480');
```

![grafik](https://user-images.githubusercontent.com/64581222/112716145-e1634880-8ee4-11eb-9b92-61dcb27203e5.png)

**Comment by ueen** [comment]
Yea that would of course be possible, but I think I'd prefer the tab because sometimes you loose track of background windows, don't you think?
 
Also I have code to check whether snapdrop is already opened in another tab and navigate to it, I don't know if it works across windows (it might though).

**Comment by ueen** [comment]
I'll give it a try, so you want this as an optional in background mode, right?

**Comment by ueen** [comment]
I think i did it, extensions doesnt really like `window`, so i ended up using
`				browser.windows.create({
				    url: sdURL,
				    type: "popup",
				    height: 480,
				    width: 360
				  });`

the 'not opening mutiple instances' also still works with one minor tweak.

Version 1.6 should be available shortly, try it and tell me what you think :)

**Comment by fm-sys** [comment]
Wow, that's simply great! I really like it, and it seems doing its job very well (especially that an already opened window is brought into the foreground instead of opening another one when clicking the icon) 👍 

Thanks a lot! And it almost feels like a PWA :-)

**Comment by ueen** [comment]
Hey, thanks, for the rating aswell :)

**Comment by hello-smile6** [comment]
What about a basic `for` loop to discard all but one session of Snapdrop? 
[Tab Discard API - Developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/discard)

**Comment by ueen** [comment]
I think it's a design decision how much the add-on should control other tabs, for now it just takes care of not starting more than one instance it self, but the user could open multiple tabs with snapdrop (which they shouldn't). 
If I recall correctly there its a PR in Snapdrop that might address multiple instances, maybe check it out.

**Comment by hello-smile6** [comment]
Okay, @ueen . Good point. What about a message in the popup that informs users that they can only have one active at a time and kills all but the selected primary instance?

**Comment by ueen** [comment]
Did you see this https://github.com/RobinLinus/snapdrop/pull/219 
I'm not sure if this is going anywhere, anyway if you would like to do this (maybe make it optional) I would accept the PR, otherwise I might have time next week to look into it.

**Comment by ueen** [comment]
As of now if snapdrop is running in a tab and the icon is clicked, the browser navigates to the already open tab - so there's only an issue if the user actually opens two tabs with snapdrop, and I hope that case will be handled by snapdrop itself someday (s. PR above ).
