### ISSUE TITLE
[feature request] custom server url

### ISSUE THREAD

**Issue by farfromrefug** [ueen/SnapdropFirefoxAddon#24]
Could you add support for specifying the server url?
Thanks

**Comment by ueen** [comment]
Would have to look into it, not entirely sure, some code was refactored from the website and is built into the plugin for the background service.
I would definitely accept a PR if somebody wants to work on this :)

**Comment by farfromrefug** [comment]
@ueen i dont know much about browser extensions and how it would become an option. but the url is set here https://github.com/ueen/SnapdropFirefoxAddon/blob/9cbe55e46ebeef8e67a4dd826ff2f16e6f341783/snapdrop/network.js#L68
So it would need to be an option to change the `snapdrop.net` host

**Comment by ueen** [comment]
Is this the only occurrence? Then I would be quite easy, I'll look into it later today.

**Comment by farfromrefug** [comment]
@ueen yes i think it is

**Comment by ueen** [comment]
should work in 1.9, couldnt do testing in lack of a proper (https) alternative server, maybe you can test?
https://github.com/ueen/SnapdropFirefoxAddon/releases/tag/1.9
Chrome is in the README
Firefox here https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

**Comment by farfromrefug** [comment]
@ueen it works perfectly!
Thanks a lot

**Comment by ueen** [comment]
Alright will update in the Firefox store then soon :)
