### ISSUE TITLE
Chrome extension request for PairDrop

### ISSUE THREAD

**Issue by onlytanmoy** [ueen/SnapdropFirefoxAddon#28]
Hiya, hope you doing well.

Can you please make a Chrome extension for PairDrop (https://github.com/schlagmichdoch/PairDrop)?

As you can see the dev has suggested your name here https://github.com/schlagmichdoch/PairDrop/issues/236#issuecomment-1879719865
so wanted to check with you on that.

**Comment by ueen** [comment]
Already working on it
https://github.com/schlagmichdoch/PairDrop/issues/232?notification_referrer_id=NT_kwDOAE1S17I4ODY0Mzc2MTU5OjUwNjc0Nzk#issuecomment-1879765004

**Comment by onlytanmoy** [comment]
> Already working on it [schlagmichdoch/PairDrop#232](https://github.com/schlagmichdoch/PairDrop/issues/232)

Awesome, good to know, eagerly awaited :) thank you.

**Comment by ueen** [comment]
Just so you know, you can already install this extension in chrome and set it to Pairdrop in settings, there are just a few things that might not work 100%.

06.01.2024 19:53:29 Troy ***@***.***>:

**Comment by onlytanmoy** [comment]
Ah I see, thanks.

You have mentioned (if you want to add it to Chrome Web Store, please open an issue/discussion) - I would very much like that to happen so will open a new issue.
