### ISSUE TITLE
Please add this extension to Chrome Web Store

### ISSUE THREAD

**Issue by onlytanmoy** [ueen/SnapdropFirefoxAddon#29]
As you have mentioned (if you want to add it to Chrome Web Store, please open an issue/discussion) - I would very much like that to happen and therefore opening this new issue.

**Comment by ueen** [comment]
Feel free to just do it, or do you need anything from me? :)

07.01.2024 11:31:51 Troy ***@***.***>:

**Comment by onlytanmoy** [comment]
haha, I have no idea how to do that. So will be great if you can do that when you have some time.

**Comment by ueen** [comment]
I wrote: open an issue if YOU want to add it to chrome store ;)
